import requests
import json
import time
from typing import Dict, Any

class OllamaClient:
    """
    Manages communication with the local Ollama API server.
    Handles POST requests, network errors, and implements exponential backoff.
    """

    def __init__(self, base_url: str):
        """
        Initializes the client.
        
        Args:
            base_url: The full API endpoint URL (e.g., http://localhost:11434/api/generate).
        """
        self.base_url = base_url
        print(f"Ollama Client initialized for endpoint: {self.base_url}")

    def _cleanup_json_markdown(self, response_text: str) -> str:
        """
        Removes markdown code fences (```json, ```) from the response, 
        leaving only the clean JSON content for parsing.
        """
        # Strip leading/trailing whitespace
        text = response_text.strip()
        
        # Check for JSON markdown fences
        if text.startswith('```json'):
            text = text.lstrip('```json').strip()
        elif text.startswith('```'):
            # Fallback for generic markdown fences
            text = text.lstrip('```').strip()

        if text.endswith('```'):
            text = text.rstrip('```').strip()

        return text

    def generate_content(self, payload: Dict[str, Any], max_retries: int = 5) -> str:
        """
        Sends the content generation payload to the Ollama server and retrieves the response.

        Args:
            payload: The JSON payload generated by the PromptEngine.
            max_retries: The maximum number of times to retry the request on failure.

        Returns:
            str: The generated text response from the LLM (clean text or clean JSON string), 
                 or an error message.
        """
        
        headers = {'Content-Type': 'application/json'}
        response_text = "ERROR: Failed to connect to Ollama."

        for attempt in range(max_retries):
            try:
                # 1. Send the POST request
                response = requests.post(self.base_url, headers=headers, json=payload, timeout=300)
                
                # 2. Check for successful HTTP status code
                if response.status_code == 200:
                    # Ollama's /api/generate without streaming returns a single JSON object
                    result = response.json()
                    
                    # Extract the generated content
                    if 'response' in result:
                        raw_response = result['response'].strip()
                        # Clean up markdown fences for structured output (like the fix command JSON)
                        return self._cleanup_json_markdown(raw_response)
                    else:
                        return f"ERROR: Ollama response structure unexpected. Keys received: {list(result.keys())}"
                
                # 3. Handle specific HTTP errors (e.g., 404 for model not found)
                print(f"Attempt {attempt + 1}: Ollama API returned HTTP status {response.status_code}.")
                
                # If the error is permanent (e.g., model not found), don't retry
                if response.status_code in [400, 404]:
                    return f"API ERROR ({response.status_code}): {response.text}"

            except requests.exceptions.Timeout:
                print(f"Attempt {attempt + 1}: Request timed out.")
                response_text = "ERROR: Request timed out after 5 minutes."
            except requests.exceptions.ConnectionError:
                print(f"Attempt {attempt + 1}: Connection Error. Ensure Ollama is running at {self.base_url.rsplit('/', 1)[0]}")
                response_text = "ERROR: Could not connect to Ollama server."
            except json.JSONDecodeError:
                print(f"Attempt {attempt + 1}: Failed to decode JSON response from Ollama API."
                      "This usually means the Ollama service itself returned malformed JSON.")
                response_text = "ERROR: Invalid JSON received from Ollama."
            except Exception as e:
                print(f"Attempt {attempt + 1}: An unexpected error occurred: {e}")
                response_text = f"ERROR: Unexpected exception: {e}"

            # 4. Implement Exponential Backoff and Retry
            if attempt < max_retries - 1:
                wait_time = 2 ** attempt  # 1s, 2s, 4s, 8s, ...
                print(f"Retrying in {wait_time} seconds...")
                time.sleep(wait_time)
            else:
                # Last attempt failed
                break

        return response_text
